from __future__ import annotations

import os
from pathlib import Path
from typing import List
from dev.dev_common.core_independent_utils import get_home_path

ARGUMENT_LONG_PREFIX = "--"
ARGUMENT_SHORT_PREFIX = "-"

HOME_PATH = get_home_path()

# FORMATS
LINE_SEPARATOR = f"\n{'=' * 70}\n"
LINE_SEPARATOR_NO_ENDLINE = f"{'=' * 70}"

# Markdown formatting constants
MD_NEWLINE = "\n"
MD_DOUBLE_NEWLINE = "\n\n"
MD_TRIPLE_NEWLINE = "\n\n\n"
MD_HORIZONTAL_RULE = "\n---\n"
MD_BLOCKQUOTE_PREFIX = "\n> "
MD_LIST_INDENT = "  "

# Markdown wrapper constants
MD_BOLD_WRAPPER = "**"
MD_ITALIC_WRAPPER = "*"
MD_STRIKETHROUGH_WRAPPER = "~~"
MD_UNDERLINE_WRAPPER = "_"
MD_CODE_WRAPPER = "`"
MD_CODE_BLOCK_WRAPPER = "```"

# Obsidian
OBSIDIAN_VAULT_NAME = "ObsidianWorkVault"  # The exact name of your Obsidian vault.
OBSIDIAN_VAULT_PATH = f"{HOME_PATH}/obsidian_work_vault"  # The full local path to your vault.

# GL
GL_BASE_URL = "https://gitlab.com"
INTELLIAN_ADC_GROUP = "intellian_adc"
PROTOTYPING_SUB_GROUP = "prototyping"
GERRIT_OW = "gerrit_mirror/oneweb"

# IESA REPO_NAMES
IESA_OW_SW_TOOLS_REPO_NAME = "oneweb_project_sw_tools"
IESA_TISDK_TOOLS_REPO_NAME = "tisdk_tools"
IESA_INTELLIAN_PKG_REPO_NAME = "intellian_pkg"
IESA_INSENSE_SDK_REPO_NAME = "insensesdk"
IESA_ADC_LIB_REPO_NAME = "adc_lib"
IESA_SPIBEAM_REPO_NAME = "submodule_spibeam"
IESA_UPGRADE_REPO_NAME = "upgrade"
IESA_ALL_COMPONENT_REPO_NAMES: List[str] = [IESA_TISDK_TOOLS_REPO_NAME, IESA_INTELLIAN_PKG_REPO_NAME,
                                       IESA_INSENSE_SDK_REPO_NAME, IESA_ADC_LIB_REPO_NAME, IESA_SPIBEAM_REPO_NAME, IESA_UPGRADE_REPO_NAME]
IESA_ALL_REPO_NAMES: List[str] = [IESA_OW_SW_TOOLS_REPO_NAME] + IESA_ALL_COMPONENT_REPO_NAMES
# IESA GL TOKEN KEYS
GL_OW_SW_TOOLS_TOKEN_KEY_NAME = "GITLAB_OW_SW_TOOLS_TOKEN"
GL_TISDK_TOKEN_KEY_NAME = "GITLAB_TISDK_TOKEN"
GL_INSENSE_SDK_TOKEN_KEY_NAME = "GITLAB_INSENSE_SDK_TOKEN"
GL_ADC_LIB_TOKEN_KEY_NAME = "GITLAB_ADC_LIB_TOKEN"
GL_INTELLIAN_PKG_TOKEN_KEY_NAME = "GITLAB_INTELLIAN_PKG_TOKEN"
GL_SPIBEAM_TOKEN_KEY_NAME = "GITLAB_SPIBEAM_TOKEN"
GL_UPGRADE_TOKEN_KEY_NAME = "GITLAB_UPGRADE_TOKEN"

# NETWORKS
SSM_IP_PREFIX = "192.168"
ACU_IP = "192.168.100.254"
ACU_USER = "root"
ACU_VAR_LOG_PATH = Path("/var/log")
ACU_FLASH_LOGS_PATH = Path("/home") / ACU_USER / "flash_logs/"
LIST_MP_IPS = [F"{SSM_IP_PREFIX}.100.54", F"{SSM_IP_PREFIX}.100.56", F"{SSM_IP_PREFIX}.100.57", F"{SSM_IP_PREFIX}.100.60",
               F"{SSM_IP_PREFIX}.100.61", F"{SSM_IP_PREFIX}.100.62", F"{SSM_IP_PREFIX}.100.64"]
LIST_FD_IPS = [F"{SSM_IP_PREFIX}.101.79", F"{SSM_IP_PREFIX}.101.126"]
LIST_HD_IPS = [F"{SSM_IP_PREFIX}.101.65", F"{SSM_IP_PREFIX}.100.70",F"{SSM_IP_PREFIX}.100.85", F"{SSM_IP_PREFIX}.101.97", F"{SSM_IP_PREFIX}.100.107"]
# PATHS
DOWNLOAD_FOLDER_PATH = HOME_PATH / "downloads"
CORE_REPOS_PATH = HOME_PATH / "workspace" / "intellian_core_repos"
LOCAL_TOOL_REPO_PATH = CORE_REPOS_PATH / "local_tools"
AVAILABLE_TOOLS_PATH = LOCAL_TOOL_REPO_PATH / "available_tools"
CREDENTIALS_FILE_PATH = LOCAL_TOOL_REPO_PATH / ".my_credentials.env"
WORKSPACE_PATH = HOME_PATH / "workspace"
CORE_REPOS_PATH = WORKSPACE_PATH / "intellian_core_repos/"
OW_SW_PATH = CORE_REPOS_PATH / "oneweb_project_sw_tools"
TEMP_PATH = "/tmp/local_tools_workdir/"
PERSISTENT_TEMP_PATH = LOCAL_TOOL_REPO_PATH / "temp"
ACU_LOG_PATH = PERSISTENT_TEMP_PATH / "acu_logs/"
GIT_REPO_PATH = WORKSPACE_PATH / "other_projects" / "git-repo/"

INSENSE_SDK_REPO_PATH = CORE_REPOS_PATH / IESA_INSENSE_SDK_REPO_NAME
DOWNLOADS_PATH = HOME_PATH / "downloads"

OW_SW_OUTPUT_IESA_PATH = OW_SW_PATH / "install_iesa_tarball.iesa"
OW_SW_BUILD_FOLDER_PATH = OW_SW_PATH / "tmp_build/"
OW_SW_BUILD_TOOLS_PATH = OW_SW_PATH / "tools" / "build_tools/"
OW_SW_KIM_FTM_FW_PATH = OW_SW_PATH / "packaging/opt_etc/kim_ftm_fw/"
OW_SW_KIM_RCVR_VERSION_FILE_PATH = OW_SW_KIM_FTM_FW_PATH / "kim_rcvr_version.txt"
OW_SW_BUILD_OUTPUT_FOLDER_PATH = OW_SW_BUILD_FOLDER_PATH / "out"
OW_SW_BUILD_BINARY_OUTPUT_PATH = OW_SW_BUILD_OUTPUT_FOLDER_PATH / "bin"

IESA_MANIFEST_RELATIVE_PATH = f"tools/manifests/iesa_manifest_gitlab.xml"
IESA_MANIFEST_FILE_PATH_LOCAL = OW_SW_PATH / IESA_MANIFEST_RELATIVE_PATH
NOTE_AVAILABLE_LOCAL_COMPONENT_REPO_NAMES = f"Available local repo names: [{', '.join(IESA_ALL_COMPONENT_REPO_NAMES)}]"
NOTE_AVAILABLE_LOCAL_REPO_NAMES = f"Available local repo names: [{', '.join(IESA_ALL_REPO_NAMES)}]"
# WSL COMMANDS
CMD_EXPLORER = "explorer.exe"
CMD_GITINGEST = "gitingest"
CMD_GIT = "git"
WSL_SELECT_FLAG = "/select,"

# SYMBOLS
UNDERSCORE = "_"
HYPHEN = "-"

OBSIDIAN_API_TOKEN_KEY_NAME = "OBSIDIAN_API_TOKEN"
JIRA_API_TOKEN_KEY_NAME = "JIRA_API_TOKEN"
JIRA_COMPANY_URL_KEY_NAME = "JIRA_COMPANY_URL"
JIRA_USERNAME_KEY_NAME = "JIRA_USERNAME"

MANIFEST_SOURCE_LOCAL = "local"
MANIFEST_SOURCE_REMOTE = "remote"
BUILD_TYPE_IESA = "iesa"
BUILD_TYPE_BINARY = "binary"

# File extensions and suffixes
FILE_PREFIX = "file_"
FOLDER_PREFIX = "folder_"
DOT_GIT = ".git"
GIT_SUFFIX = DOT_GIT
TXT_EXTENSION = ".txt"

# Argument name constants
ARG_VERSION_OR_FPKG_FW_PATH = f"{ARGUMENT_LONG_PREFIX}version_or_fpkg_path"
ARG_DEFAULT_OW_MANIFEST_BRANCH = f"{ARGUMENT_LONG_PREFIX}ow_default_manifest_branch"
ARG_TOOL_PREFIX = f"{ARGUMENT_LONG_PREFIX}prefix"
ARG_TOOL_FOLDER_PATTERN = f"{ARGUMENT_LONG_PREFIX}folder_pattern"
# Allow overriding the root directory containing all tool folders
ARG_TOOLS_DIR = f"{ARGUMENT_LONG_PREFIX}tools_dir"
# ARG_TOOL_ROOT_PATH = f"{ARGUMENT_LONG_PREFIX}root_path"
ARG_PATH_LONG = f"{ARGUMENT_LONG_PREFIX}path"
ARG_PATHS_LONG = f"{ARGUMENT_LONG_PREFIX}paths"
ARG_PATH_SHORT = f"{ARGUMENT_SHORT_PREFIX}p"
ARG_PATHS_SHORT = f"{ARGUMENT_SHORT_PREFIX}p"
ARG_TICKET_URL = f"{ARGUMENT_LONG_PREFIX}jira_url"
ARG_OUTPUT_DIR = f"{ARGUMENT_LONG_PREFIX}output_dir"
ARG_OUTPUT_DIR_SHORT = f"{ARGUMENT_SHORT_PREFIX}o"
ARG_NO_OPEN_EXPLORER = f"{ARGUMENT_LONG_PREFIX}no-open-explorer"
ARG_MAX_FOLDERS = f"{ARGUMENT_LONG_PREFIX}max-folders"
ARG_IS_GEN_CODING_TASK = F"{ARGUMENT_LONG_PREFIX}is_gen_coding_task"
ARG_TEMPLATE_PATH = f"{ARGUMENT_LONG_PREFIX}template_path"
ARG_VAULT_PATH = f"{ARGUMENT_LONG_PREFIX}vault_path"
ARG_NOTE_REL_PATH = f"{ARGUMENT_LONG_PREFIX}dir_to_copy_to"
ARG_NOTE_REL_PATHS_TO_ADD_CONTENT = f"{ARGUMENT_LONG_PREFIX}paths_to_link_from"
ARG_MODE = f"{ARGUMENT_LONG_PREFIX}mode"
ARG_REPO_NAME = f"{ARGUMENT_LONG_PREFIX}repo_name"
ARG_SOURCE_BRANCH = f"{ARGUMENT_LONG_PREFIX}source_branch"
ARG_TARGET_BRANCH = f"{ARGUMENT_LONG_PREFIX}target_branch"
ARG_INTERACTIVE = f"{ARGUMENT_LONG_PREFIX}interactive"
ARG_IS_CREATE_GL_MR = f"{ARGUMENT_LONG_PREFIX}is_create_gl_mr"
# ARG VALUES
EMPTY_STR_VALUE = ""
TRUE_STR_VALUE = "true"
FALSE_STR_VALUE = "false"
BRANCH_MANPACK_MASTER = "manpack_master"
BRANCH_MASTER = "master"
OW_MAIN_BRANCHES = [BRANCH_MANPACK_MASTER, BRANCH_MASTER]

# Common argument names for Inertial Sense tools
ARG_UPDATE_FW = f"{ARGUMENT_LONG_PREFIX}update_fw"
ARG_UPDATE_SDK = f"{ARGUMENT_LONG_PREFIX}update_sdk"
ARG_FPKG_ONLY = f"{ARGUMENT_LONG_PREFIX}fpkg_only"
ARG_NO_PROMPT = f"{ARGUMENT_LONG_PREFIX}no_prompt"
ARG_SDK_PATH = f"{ARGUMENT_LONG_PREFIX}sdk_path"
ARG_OW_SW_BASE_BRANCH = f"{ARGUMENT_LONG_PREFIX}ow_sw_base_branch"
ARG_INSENSE_CL_BASE_BRANCH = f"{ARGUMENT_LONG_PREFIX}insense_cl_base_branch"
ARG_SDK_BRANCH = f"{ARGUMENT_LONG_PREFIX}sdk_branch"
ARG_SDK_BRANCH_OR_TAG = f"{ARGUMENT_LONG_PREFIX}sdk_branch_or_tag"

# Emojis
SUCCESS_EMOJI = "✅"
FAILURE_EMOJI = "❌"
CELEBRATION_EMOJI = "🎉"

# Messages
LOG_PREFIX_MSG_INFO = "[INFO]"
LOG_PREFIX_MSG_SUCCESS = "[SUCCESS]"
LOG_PREFIX_MSG_ERROR = "[ERROR]"
LOG_PREFIX_MSG_WARNING = "[WARNING]"
LOG_PREFIX_MSG_FATAL = "[FATAL]"
