LINE_SEPARATOR = f"\n{'=' * 60}\n"
GL_TISDK_TOKEN_KEY_NAME = "GITLAB_TISDK_TOKEN"

MANIFEST_SOURCE_LOCAL = "local"
MANIFEST_SOURCE_REMOTE = "remote"
BUILD_TYPE_IESA = "iesa"
BUILD_TYPE_BINARY = "binary"